name: Unit test

on:
  push:
    branches:
      - '**'  # On push every branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Set up Cache
        uses: actions/cache@v3
        with:
          path: |
            build
            ~/.cache
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-

      - name: Initialize submodule
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake libopenmpi-dev openmpi-bin

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Test
        run: cd build && ./test_multiplication
