name: Unit test

on:
  push:
    branches:
      - '**'  # On push every branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v7

      - name: Verify Singularity Installation
        run: singularity --version

      - name: Set up Cache
        uses: actions/cache@v4
        with:
          path: |
            build
            ~/.cache
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-

      # - name: Download go
      #   run: export VERSION=1.11 OS=linux ARCH=amd64 && wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz && sudo tar -C /usr/local -xzvf go$VERSION.$OS-$ARCH.tar.gz && rm go$VERSION.$OS-$ARCH.tar.gz

      # - name: Set up go
      #   run: echo 'export GOPATH=${HOME}/go' >> ~/.bashrc && echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc && source ~/.bashrc

      # - name: Install Go dep
      #   run: cd /home/runner/go/ mkdir bin && curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

      - name: Initialize submodule
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake libopenmpi-dev openmpi-bin #libssl-dev uuid-dev libgpgme11-dev squashfs-tools libseccomp-dev pkg-config

      # - name: Install singularity
      #   run: go get -d github.com/sylabs/singularity

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Test
        run: cd build && ./test_multiplication

      - name: Build Singularity image
        run: singularity build TestMultiplication.sif Singularity.def
